/*
pow, max, min & sqrt
round a number
  - round 
  - toStringAsFixed
  
Random number
  - Get random number 0 - 9
  - Get random number 1 - 10
  - Generate random number between any number range
  - Get random boolean value 
  - Get random double Value
  - Generate a list of 15 random numbers between 100 to 1000

Creating a random number guessing game:
A number has been generated by the system from 1 - 100. Try to guess it.

Enter your guess: 50
Your guess is low, try again

Enter your guess: 80
Your guess is high, try again

Congratulations, you have guessed the number.
Congratulations, you have guessed the number in 10 attempts.
*/

// import 'dart:math';

// void main(List<String> args) {
//   Random random = Random();
//   List<int> listOfNum = List.generate(15, (index) => random.nextInt(100) + 1);
//   print(listOfNum);
// }

// import 'dart:io';
// import 'dart:math';

// void main(List<String> args) {
//   int numX, userGuess;
//   Random random = Random();

//   numX = random.nextInt(100) + 1;
//   // print(numX);
//   print(
//       'A number has been generated by the system from 1 - 100.\nTry to guess it.');

//   while (true) {
//     stdout.write('Enter your guess: ');
//     userGuess = int.parse(stdin.readLineSync()!);

//     if (userGuess > numX) {
//       print('Your guess is high, try again');
//     } else if (userGuess < numX) {
//       print('Your guess is low, try again');
//     } else {
//       break;
//     }
//   }

//   print('Congratulations, you have guess the number.');
// }
