/*
pow, max, min & sqrt
round a number
  - round 
  - toStringAsFixed
  
Random number
  - Get random number 0 - 9
  - Get random number 1 - 10
  - Generate random number between any number range
  - Get random boolean value 
  - Get random double Value
  - Generate a list of 15 random numbers between 100 to 1000

Creating a random number guessing game:
A number has been generated by the system from 1 - 100. Try to guess it.

Enter your guess: 50
Your guess is low, try again

Enter your guess: 80
Your guess is high, try again

Congratulations, you have guessed the number.
Congratulations, you have guessed the number in 10 attempts.
*/

import 'dart:math';

void main(List<String> args) {
  // pow, max, min & sqrt
  // print(pow(5, 2)); // 25
  // print(max(17, 31)); // 31
  // print(min(17, 31)); // 17
  // print(sqrt(625)); // 25.0

  // round a number
  double x = 5.13589745;
  print(x.round());

  // toStringAsFixed
  print(x.toStringAsFixed(2));
}
